(ns steadyhash.maglev
  (:require [steadyhash.lib :refer [next-prime h1 h2]]))

(defn permutations
  "Lazy seq of permutations for a node"
  [m id]
  (let [offset (-> id h1 (mod m))
        skip (-> id h2 (mod (dec m)) inc)]
    (for [j (range m)]
      (-> j (* skip) (+ offset) (mod m)))))

(defn populate
  "Populate Maglev hashing lookup table
  (See Maglev paper page 6)"
  ([nodes] (populate nodes (-> nodes count (* 100) next-prime)))
  ([nodes m]
   (loop [entries {}
          node-seq (cycle (sort nodes))
          preferences (into {} (for [node nodes] [node (permutations m node)]))
          n 0]
     (let [[node & next-nodes] node-seq
           [entry & next-entries] (preferences node)
           next-prefs (assoc preferences node next-entries)]
       (if (= n m)
         (->> entries (into (sorted-map)) vals vec) ; return as a vector
         (if (entries entry) ; If slot already taken,
           (recur entries node-seq next-prefs n) ; try again with same node.
           (recur (assoc entries entry node) next-nodes next-prefs (inc n))))))))

(defn lookup
  "Use a lookup table generated by populate to determine node assigned to x"
  [table x]
  (-> x h1 (mod (count table)) table))

(comment
  ;; Example:
  (def table (populate [:a :b :c :d]))
  (lookup table :foo) ; => :d
  (lookup table :bar) ; => :c

  (frequencies table) ; => {:c 100, :b 100, :d 100, :a 101}

  (->> (pmap (partial lookup table) (range 4e5))
    frequencies)
  ;; => {:d 99547, :a 100924, :c 99628, :b 99901}
)
